### PR TITLE
Allow setting host at runtime

### PR DESCRIPTION
**Pull request by jjcarstens**

### CODE REVIEW

**Comment by jjcarstens** [comment]
Updated the README.md

This shouldn't lose any services. It updates the state for only the host and host alias without touching anything else. Unless there is some specific mDNS stuff happening in the background that can't deal with the hostname change?

**Comment by jjcarstens** [comment]
Though in looking over this again, I do think there is a little more work to update any existing `MdnsLite.Responder`s children that are running so that they have the new config. I'll try to get to that shortly

**Comment by pcmarks** [comment]
I was wrong. 
Sorry, but I won't be working until late afternoon on Monday although I'll be able to go online, periodically, and check my mail,  etc.

**Comment by jjcarstens** [comment]
K, I've updated with 2 new commits to handle updating existing responders when a config change happens (host, services, etc). Also also a test for it. Should be ready to go

**Comment by jjcarstens** [comment]
Ill fix this quick and bring it up to date

**Comment by pcmarks** [comment]
I ran the tests with elixir 1.8.2-opt-22 and they all worked!

If one goes to the *details* of the failed test, there is a button in the upper right hand that says *"Rerun workflow."* However it's disabled because I don't have write permission. As the owner/collaborator I thought I had that permission.

**Comment by jjcarstens** [comment]
Just FYI, have been doing some testing with this and things are looking 👌 

(shows pinging `nerves.local`, then changing host and being able to ping new host and alias)
image

**Comment by pcmarks** [comment]
Thanks for your patience, Jon. I had some appointments but, also, I had to figure out how to rerun the CI tests. I did and all is good.

I'll create a new release around dinner time.

**Pull request merged**
